### PR TITLE
Various

### PR DESCRIPTION
**Pull request by jelu**
I found these changes that @klaus3000 (Thanks!) made a long time ago, cherry picked almost all in and modified them some because of recent changes. I think that only new option that was not included is the workaround for libpcap collection during low traffic, that has been solved by using pcap-thread #18.

@vixie & @wessels, do any of you want to comment the various new options and changes?

### CODE REVIEW

**Comment by wessels** [comment]
Looks good to me.

**Comment by vixie** [comment]
this is wrong

-.Op nytfsxir
+.Op nytfsxirMC

the new option is D not C.

**Comment by vixie** [comment]
`@@ -940,6 +946,11 @@ parse_args(int argc, char *argv[]) {
 			else
 				dump_type = to_file;
 			break;
+		case 'W':
+		    if (dump_suffix)
+		        free(dump_suffix);
+			dump_suffix = strdup(optarg);
+			break;
 		case 'k':
 			if (dump_type != to_file)
 				usage("-k depends on -w"

is there an indentation problem here?`

**Comment by vixie** [comment]
the rest of this file is in BSD KNF. therefore no braces should be used around single statements.

+		if (preso) {
+			goto breakloop;
+		}
+		if (dumper_opened == dump_state && dumper_close(hdr->ts)) {
+			goto breakloop;
+		}

**Comment by jelu** [comment]
@vixie Indentation and braces are not really a problem, I prefer bracers and spaces. Please see https://guides.github.com/features/mastering-markdown/ on how Markdown can quote code in comments for next time.

**Comment by vixie** [comment]
jerry, i'll look up the markdown question, but really, please keep any 
source files in a single consistent style, ideally the one it started 
with. --paul

**Comment by vixie** [comment]
ok so i looked at .../mastering-markdown/ and github has no special 
syntax beyond `backticks` which i did in fact use. github's markdown 
parser decided that the + symbols from the diff output were bullets, 
even though they appeared inside `backticks`. this is, to me, a bug.

**Comment by jelu** [comment]
@vixie sadly, Markdown is not rendered from emails

**Comment by vixie** [comment]
Jerry Lundström wrote:
> @vixie <https://github.com/vixie> sadly, Markdown is not rendered from
> emails

let me be clear, and let me suggest that you test the same thing i did.

i went into the github web UI and where it gave me a text box that 
allowed me to enter a comment, i cut and pasted some diff output and put 
it inside `backticks`. email was not involved. on my screen i saw:

`+   blah
+   blah
+   blah`

when i looked at the preview i saw

* blah
* blah
* blah

i tried changing + to \+ without result.

again, no e-mail was involved.

github's markdown renderer is expanding + to bullets even inside code 
snippets. this is unlike any other markdown renderer i have used, and i 
consider it a bug.

-- 
P Vixie

**Comment by jelu** [comment]
@vixie You are doing it a bit wrong, for inline code quotes a single backtick is the way but for multi-line code you should use 3 backticks and a newline before pasting the code. Look at the link -> Examples -> Code.

**Comment by vixie** [comment]
ok thanks.

did you really commit #23 over my objection, btw?

**Comment by jelu** [comment]
@vixie Sorry, was there an issue with the code (disregarding indentation)?

**Comment by vixie** [comment]
Jerry Lundström wrote:
> @vixie <https://github.com/vixie> Sorry, was there an issue with the
> code (disregarding indentation)?

is my mail not getting through?

the file was written in BSD KNF. other than this patch, it is 
consistent. if you're not going to maintain consistency, tell me now. if 
you are, then you ought to remove the braces around any single 
statement, since that's not BSD KNF.

-- 
P Vixie

**Comment by jelu** [comment]
@vixie If you wish to change the code submitted by @klaus3000 to fit the coding standard you wish to use then please go ahead and make a pull request, for me that time can be spent on better things. As for consistency, I value other types more like having the code actually compile and work on the decided supported platforms. This project could really use some tests for example.

**Comment by vixie** [comment]
Jerry Lundström wrote:
> @vixie <https://github.com/vixie> If you wish to change the code
> submitted by @klaus3000 <https://github.com/klaus3000> to fit the coding
> standard you wish to use then please go ahead and make a pull request,
> for me that time can be spent on better things.

understood. is it still the case that to make a pull request i must 
first clone the repo, since there's no way for outsiders to make branches?

> As for consistency, I value other types more like having the code
> actually compile and work on the decided supported platforms. This
> project could really use some tests for example.

when i first donated dnscap to dns-oarc, it built and ran properly on 
freebsd, debian, and mac/os. i agree that i demonstrated laziness by not 
also including regression tests, and by not using gnu autoconf.

please hear this plea for consistency: if a patch does not follow the 
coding standard that's consistently used throughout the rest of the 
file, please reject it, and ask that it be resubmitted either using the 
existing style, or as a much larger patch that changes the style 
consistently to be the new way. "good fences make good neighbors."

-- 
P Vixie

**Comment by jelu** [comment]
@vixie To contribute you must first fork the repository to your own account then you can clone it from there and please use feature branches when doing pull requests so it is easier for you to keep in sync with the upstream repository.

Example for clone, feature branch:
```
git clone git@github.com:vixie/dnscap.git
cd dnscap
git checkout -b feature-xyz develop
vi ...
git commit -m "Add feature XYZ" files
git push -u origin feature-xyz
```

Then create pull request from branch `feature-xyz`.

To keep in sync:
```
cd dnscap
git remote add upstream https://github.com/DNS-OARC/dnscap.git
git fetch --all -pt
git checkout develop
git merge --ff-only upstream/develop
git push origin develop
```

**Comment by vixie** [comment]
thanks for that. i can follow those directions. i just hate forking, 
because inevitably someone will clone my fork and that makes chaos. this 
is why in the projects i'm in core for, we allow feature branches in the 
real repo. it's far less likely that someone will end up running a 
feature branch (vs. a stale clone) in production, or shipping it.

perhaps i should pay github the fee for a private (non-clonable) repo.

**Pull request merged**
