### PR TITLE
-B <begin> and -E <end> can work fine without -w <base>.

### PR DESCRIPTION
**Pull request by wessels**

### CODE REVIEW

**Comment by jelu** [comment]
Since this is a restriction that's been around for 9+ years, can you add some tests for this?

Also, what are the use cases for you to use `-B`/`-E` without `-w`?

**Comment by wessels** [comment]
test9.sh has been added.

The use case is that I want to capture for a specific window of time, but I don't want to generate an output (pcap) file.  The restriction was put in place many years before the plugins were developed.  Now I want to process packets with a plugin, but control the time window of the capture.

**Comment by jelu** [comment]
Looking at the output of the test, the `-B` flags does not seem to work. `2016-10-20 15:23:30` is specified by DNS from earlier are shown. `-E` seems to work.

**Comment by jelu** [comment]
#build

**Comment by jelu** [comment]
@wessels Can you check the man-page with the changes? Easiest way of reading it is to pull the changes, `make` and then do `man src/dnscap.1`.

**Comment by jelu** [comment]
#build

**Comment by wessels** [comment]
Thanks for updating the man page.  It looks good to me.

**Pull request merged**
