### PR TITLE
Adding support for label acount metric

### PR DESCRIPTION
**Pull request by kdrenard**
Adding support for label count metric.

### CODE REVIEW

**Comment by jelu** [comment]
@kdrenard found the presentation from ICANN 74, do you have an estimate on when RSSAC002v5 will be finalized?

**Comment by kdrenard** [comment]
The work party for RSSAC002 updates will take a while (est 4-6 months?).
We could either wait until that is done, or I am currently working on
making this 'optional' in RSSM: a flag to turn it ON and a flag to specify
the number of label counts to collect.  If you can hold on a bit before
release, I should be able to get the option piece put in today or Tuesday.
Either way, I am fine.

Thanks!

-Ken

**Comment by jelu** [comment]
@kdrenard an opt-in flag would be better but that's not really my main concern. It's that you're tagging this metric as `version: rssac002v3` which it's definitely not :smile:

**Comment by jelu** [comment]
ah you already said opt-in, sorry :)

**Comment by jelu** [comment]
If this is coming in rssac002v5 and it's an opt-in flag then just use `rssac002v5`

**Comment by jelu** [comment]
Is there a reason behind limiting max labels?

It's not like there is much difference between 34 and 63 ints.

**Comment by kdrenard** [comment]
The idea behind max_labels was to manage output size.  There is very little useful information in the distribution for 34+ labels.  Computationally and memory-wise, there is very little difference.  Other tools (packetq, dsc) do not have a limit, as they allocate dynamically.  Managing output size can be done outside of dnscap as well.

If you would prefer a static array of label counters, I would be fine taking out the allocated one.

**Comment by kdrenard** [comment]
Computationally and memory-wise, there is very little difference.  It's
more about managing the output and aggregating lots of text output across
time periods and some number of instances to get to a daily total per RSO.

-Ken

**Pull request merged**
